language: generic

dist: bionic

before_install:
    - sudo add-apt-repository -y ppa:bartbes/love-stable
    - sudo apt-get update
    - sudo apt-get install -y lua-check love mercurial

jobs:
    include:
        - script: luacheck .
        - stage: GitHub Release
          script: ./build.sh
          deploy:
              provider: releases
              api_key: "$GITHUB_OAUTH_TOKEN"
              file_glob: true
              file: dist/*
              draft: true
              skip_cleanup: true
              on:
                  branch: master
